version: "3"
services:
  assignment-app:
    container_name: assignment-app
    build:
      context: .
      dockerfile: .Dockerfile
    depends_on:
      - postgres
    environment:
      PSQL_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-assignment-db}
      JWT_SECRET: ${JWT_SECRET:-you@talking@to@me?}
      JWT_ALGO: ${JWT_ALGO:-HS256}
      USER_EMAIL: ${USER_EMAIL:-admin123@yopmail.com}
      USER_PWD: ${USER_PWD:-Test@123}
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
  postgres:
    container_name: postgres
    image: postgres:10.4
    ports:
      - "5431:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      # - ./src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: assignment-db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: assignment@node.com
      PGADMIN_DEFAULT_PASSWORD: test123
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
volumes:
    db-data:
    pgadmin-data:
